name: venv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=1.2.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.2.0
  - certifi=2022.9.14
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.1.0
  - contourpy=1.0.5
  - cpuonly=1.0
  - cryptography=37.0.4
  - cudatoolkit=11.6.0
  - cudnn=8.4.1.50
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.4.8
  - flatbuffers=2.0.7
  - fontconfig=2.14.0
  - fonttools=4.37.3
  - freetype=2.12.1
  - frozenlist=1.3.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.72.1
  - glib-tools=2.72.1
  - google-auth=2.11.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.46.4
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gym=0.21.0
  - h5py=3.7.0
  - hdf5=1.12.2
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.4
  - iniconfig=1.1.1
  - intel-openmp=2022.1.0
  - jpeg=9e
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libabseil=20211102.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.84.0
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.72.1
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsqlite=3.39.3
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.12
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.6.0
  - matplotlib-base=3.6.0
  - mkl=2022.1.0
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.3
  - ninja=1.11.0
  - numpy=1.23.3
  - oauthlib=3.2.1
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - opt_einsum=3.3.0
  - packaging=21.3
  - pcre=8.45
  - pillow=9.2.0
  - pluggy=1.0.0
  - pthread-stubs=0.4
  - py=1.11.0
  - pyasn1=0.4.8
  - pycparser=2.21
  - pyjwt=2.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pysocks=1.7.1
  - pytest=7.1.3
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python_abi=3.8
  - pytorch=1.4.0
  - pytweening=1.0.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - qt=5.9.7
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scipy=1.7.3
  - setuptools=62.3.4
  - sip=4.19.13
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.39.3
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.9.1
  - tensorflow-base=2.9.1
  - termcolor=2.0.1
  - tk=8.6.12
  - tomli=2.0.1
  - torchaudio=0.4.0
  - torchvision=0.5.0
  - tornado=6.2
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - unicodedata2=14.0.0
  - werkzeug=2.2.2
  - wheel=0.37.1
  - wrapt=1.14.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2